name:  services
description:  High-level libraries for isolate-isolate communication.

dependencies:
  unittest:
    sdk: unittest
  logging:
    sdk: logging
  browser: any
  serialization:
    sdk: serialization